### ISSUE TITLE
Support Header / Footer styling

### ISSUE THREAD

**Issue by drom** [wavedrom/datasheet#25]
```css
 @page {
    @top-center {
      content: "top-center"; border: solid green;
    }
    @bottom-center {
      content: counter(pageNumber); border: solid blue;
    }
  }

  @page :first {
    @top-center {
      content: "top-center-first"; border: solid green;
    }
    @bottom-center {
      content: "bottom-center-first"; border: solid blue;
    }
  }
```
https://developer.mozilla.org/en-US/docs/Web/CSS/page
https://developer.mozilla.org/en-US/docs/Web/CSS/@page

Available in chrome v131
